#!/usr/bin/env python
import qutip
import numpy
import json
import time

start = time.time()

print('Hello World')

end = time.time()

t = end - start

print(t)

with open("/home/ucapcli/Scratch/GroupProject/results/hellotime.json","w") as write_file:
    json.dump(t, write_file)
